sudo : required

matrix:
    include:
        - os : osx
          osx_image: xcode10
        - os: osx
          osx_image: xcode9
        - os: linux
          sudo: required

services:
    - docker

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build_wheels_osx.sh      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make   ; fi
