sudo : required

os:
    - linux
    - osx

matrix:
    include:
        - osx_image: xcode10
        - osx_image: xcode9

services:
    - docker

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build_wheels_osx.sh      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make   ; fi
