matrix:
  include:
    - os: osx
      osx_image: xcode12
    - os : osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode10
    - os: linux


services:
  - docker


notifications:
  email:
    recipients:
      - dilawar.s.rajput@gmail.com
    on_success: change
    on_failure: always

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build_wheels_osx.sh      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make   ; fi
