sudo : required

os:
    - linux
    - osx

services:
    - docker

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; ./build_wheels_osx.sh      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; make   ; fi
